# A unique name, must eq var console/vite.config.js#pluginEntryName,
# and can not contain specific symbol such as - .
name: PluginWebdav
# plugin entry class that extends BasePlugin
clazz: run.ikaros.plugin.webdav.StarterPlugin
# plugin 'version' is a valid semantic version string (see semver.org).
version: 0.13.0
requires: ">=0.13.0"
author:
  name: Ikaros OSS Team
  website: https://github.com/ikaros-dev
logo: https://ikaros.run/logo.png
homepage: https://github.com/ikaros-dev/plugin-webdav
displayName: "Webdav插件"
description: "Webdav插件"
license: "AGPL-3.0"